# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitto < Formula
  desc "Multi-repo Git TUI workspace manager"
  homepage "https://github.com/jack-braga/gitto"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jack-braga/gitto/releases/download/v0.1.0/gitto_0.1.0_darwin_arm64.tar.gz"
      sha256 "53fc8f37bb119aa740ce4991061382bbb4fc904c439c43ba1156c7641a7bbb7e"

      define_method(:install) do
        bin.install "gitto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jack-braga/gitto/releases/download/v0.1.0/gitto_0.1.0_linux_arm64.tar.gz"
      sha256 "4e35c93c26a46f4fcf26873ff8b76aacf5aab95f6b28f8293acb9f8feafc309f"
      define_method(:install) do
        bin.install "gitto"
      end
    end
  end

  test do
    system "#{bin}/gitto", "--version"
  end
end
