# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitto < Formula
  desc "Multi-repo Git TUI workspace manager"
  homepage "https://github.com/jack-braga/gitto"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jack-braga/gitto/releases/download/v0.1.1/gitto_0.1.1_darwin_arm64.tar.gz"
      sha256 "09f704f85c1b68edcfba3ea3b02c980f35c23171109778d63d4ccc42e9dd0c6f"

      define_method(:install) do
        bin.install "gitto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jack-braga/gitto/releases/download/v0.1.1/gitto_0.1.1_linux_arm64.tar.gz"
      sha256 "dfca785c3a9fa4a2ac5889f08e981cbb6a2f8a0ae1a2fb5edd631e2317671c29"
      define_method(:install) do
        bin.install "gitto"
      end
    end
  end

  test do
    system "#{bin}/gitto", "--version"
  end
end
